# Generated by Django 4.2.30 on 2026-06-19 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_app/group_avatars/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='image',
            field=models.ImageField(upload_to='chat_app/message_images/'),
        ),
    ]
