# Generated by Django 6.0.4 on 2026-05-15 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profileapp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileApp',
            new_name='Profile',
        ),
    ]
