# Generated by Django 6.0.4 on 2026-05-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudonym',
        ),
    ]
