# Generated by Django 6.0.4 on 2026-05-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
