# Generated by Django 6.0.4 on 2026-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='compressed',
            field=models.ImageField(upload_to='post_images/compressed'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='original',
            field=models.ImageField(upload_to='post_images/originals'),
        ),
    ]
