# Generated by Django 6.0.4 on 2026-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_postimage_compressed_alter_postimage_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='compressed',
            field=models.ImageField(upload_to='post_images/compressed/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='original',
            field=models.ImageField(upload_to='post_images/originals/'),
        ),
    ]
