# Generated by Django 4.2.30 on 2026-06-19 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_alter_postimage_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='PostLink',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='compressed',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='original',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postimage',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_app/compressed_images/'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_app/original_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
